// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjwmf4nXzjxDxWpzrBEwbTFt7vsJkYURs',
    appId: '1:665195774844:web:432ed5730c9c5f0e6f9af9',
    messagingSenderId: '665195774844',
    projectId: 'crud-pruebakh',
    authDomain: 'crud-pruebakh.firebaseapp.com',
    storageBucket: 'crud-pruebakh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2liNEedm8wob26wE_BLAfxx43Y8RelYg',
    appId: '1:665195774844:android:788a7761bf8760b16f9af9',
    messagingSenderId: '665195774844',
    projectId: 'crud-pruebakh',
    storageBucket: 'crud-pruebakh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOhkuAHR3QZog5dw2aoCuTnQuXWkf0Xp0',
    appId: '1:665195774844:ios:ddf93bcdaec3aca96f9af9',
    messagingSenderId: '665195774844',
    projectId: 'crud-pruebakh',
    storageBucket: 'crud-pruebakh.appspot.com',
    iosBundleId: 'com.example.prueba2Karenh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOhkuAHR3QZog5dw2aoCuTnQuXWkf0Xp0',
    appId: '1:665195774844:ios:ddf93bcdaec3aca96f9af9',
    messagingSenderId: '665195774844',
    projectId: 'crud-pruebakh',
    storageBucket: 'crud-pruebakh.appspot.com',
    iosBundleId: 'com.example.prueba2Karenh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjwmf4nXzjxDxWpzrBEwbTFt7vsJkYURs',
    appId: '1:665195774844:web:d8db7103264fd1a36f9af9',
    messagingSenderId: '665195774844',
    projectId: 'crud-pruebakh',
    authDomain: 'crud-pruebakh.firebaseapp.com',
    storageBucket: 'crud-pruebakh.appspot.com',
  );
}
